# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements_test.txt

# command to run tests using coverage, e.g. python setup.py test
script: coverage run runtests.py

after_success:
  - codecov
